// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateEarthquake struct {
	Mag         float64    `json:"mag"`
	Time        time.Time  `json:"time"`
	UpdatedTime *time.Time `json:"updatedTime,omitempty"`
	Tz          *int       `json:"tz,omitempty"`
	URL         *string    `json:"url,omitempty"`
	Detail      *string    `json:"detail,omitempty"`
	Status      *string    `json:"status,omitempty"`
	Tsunami     *int       `json:"tsunami,omitempty"`
	Sig         *int       `json:"sig,omitempty"`
	Net         *string    `json:"net,omitempty"`
	Code        *string    `json:"code,omitempty"`
	Nst         *int       `json:"nst,omitempty"`
	Dmin        *float64   `json:"dmin,omitempty"`
	Rms         *float64   `json:"rms,omitempty"`
	Gap         *float64   `json:"gap,omitempty"`
	MagType     *string    `json:"magType,omitempty"`
	EqType      *string    `json:"eqType,omitempty"`
	Place       *string    `json:"place,omitempty"`
	Address     *string    `json:"address,omitempty"`
	FeatType    *string    `json:"featType,omitempty"`
	Longitude   float64    `json:"longitude"`
	Latitude    float64    `json:"latitude"`
	Depth       float64    `json:"depth"`
	Felt        *int       `json:"felt,omitempty"`
	Cdi         *float64   `json:"cdi,omitempty"`
	Mmi         *float64   `json:"mmi,omitempty"`
	Alert       *string    `json:"alert,omitempty"`
	SourceName  *string    `json:"sourceName,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type CreateUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type EarthquakeFilter struct {
	Magnitude      *float64 `json:"magnitude,omitempty"`
	Place          *string  `json:"place,omitempty"`
	EarthquakeType *string  `json:"earthquakeType,omitempty"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type ResetPasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}
