// Code generated by ent, DO NOT EDIT.

package apireq

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.com/hedwig-phan/assignment-3/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldID, id))
}

// ReqTime applies equality check predicate on the "req_time" field. It's identical to ReqTimeEQ.
func ReqTime(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldReqTime, v))
}

// RespTime applies equality check predicate on the "resp_time" field. It's identical to RespTimeEQ.
func RespTime(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldRespTime, v))
}

// RespStatus applies equality check predicate on the "resp_status" field. It's identical to RespStatusEQ.
func RespStatus(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldRespStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldDeletedAt, v))
}

// ReqTimeEQ applies the EQ predicate on the "req_time" field.
func ReqTimeEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldReqTime, v))
}

// ReqTimeNEQ applies the NEQ predicate on the "req_time" field.
func ReqTimeNEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldReqTime, v))
}

// ReqTimeIn applies the In predicate on the "req_time" field.
func ReqTimeIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldReqTime, vs...))
}

// ReqTimeNotIn applies the NotIn predicate on the "req_time" field.
func ReqTimeNotIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldReqTime, vs...))
}

// ReqTimeGT applies the GT predicate on the "req_time" field.
func ReqTimeGT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldReqTime, v))
}

// ReqTimeGTE applies the GTE predicate on the "req_time" field.
func ReqTimeGTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldReqTime, v))
}

// ReqTimeLT applies the LT predicate on the "req_time" field.
func ReqTimeLT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldReqTime, v))
}

// ReqTimeLTE applies the LTE predicate on the "req_time" field.
func ReqTimeLTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldReqTime, v))
}

// ReqParamIsNil applies the IsNil predicate on the "req_param" field.
func ReqParamIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldReqParam))
}

// ReqParamNotNil applies the NotNil predicate on the "req_param" field.
func ReqParamNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldReqParam))
}

// ReqBodyIsNil applies the IsNil predicate on the "req_body" field.
func ReqBodyIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldReqBody))
}

// ReqBodyNotNil applies the NotNil predicate on the "req_body" field.
func ReqBodyNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldReqBody))
}

// ReqHeadersIsNil applies the IsNil predicate on the "req_headers" field.
func ReqHeadersIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldReqHeaders))
}

// ReqHeadersNotNil applies the NotNil predicate on the "req_headers" field.
func ReqHeadersNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldReqHeaders))
}

// ReqMetadataIsNil applies the IsNil predicate on the "req_metadata" field.
func ReqMetadataIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldReqMetadata))
}

// ReqMetadataNotNil applies the NotNil predicate on the "req_metadata" field.
func ReqMetadataNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldReqMetadata))
}

// RespTimeEQ applies the EQ predicate on the "resp_time" field.
func RespTimeEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldRespTime, v))
}

// RespTimeNEQ applies the NEQ predicate on the "resp_time" field.
func RespTimeNEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldRespTime, v))
}

// RespTimeIn applies the In predicate on the "resp_time" field.
func RespTimeIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldRespTime, vs...))
}

// RespTimeNotIn applies the NotIn predicate on the "resp_time" field.
func RespTimeNotIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldRespTime, vs...))
}

// RespTimeGT applies the GT predicate on the "resp_time" field.
func RespTimeGT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldRespTime, v))
}

// RespTimeGTE applies the GTE predicate on the "resp_time" field.
func RespTimeGTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldRespTime, v))
}

// RespTimeLT applies the LT predicate on the "resp_time" field.
func RespTimeLT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldRespTime, v))
}

// RespTimeLTE applies the LTE predicate on the "resp_time" field.
func RespTimeLTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldRespTime, v))
}

// RespStatusEQ applies the EQ predicate on the "resp_status" field.
func RespStatusEQ(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldRespStatus, v))
}

// RespStatusNEQ applies the NEQ predicate on the "resp_status" field.
func RespStatusNEQ(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldRespStatus, v))
}

// RespStatusIn applies the In predicate on the "resp_status" field.
func RespStatusIn(vs ...int) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldRespStatus, vs...))
}

// RespStatusNotIn applies the NotIn predicate on the "resp_status" field.
func RespStatusNotIn(vs ...int) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldRespStatus, vs...))
}

// RespStatusGT applies the GT predicate on the "resp_status" field.
func RespStatusGT(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldRespStatus, v))
}

// RespStatusGTE applies the GTE predicate on the "resp_status" field.
func RespStatusGTE(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldRespStatus, v))
}

// RespStatusLT applies the LT predicate on the "resp_status" field.
func RespStatusLT(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldRespStatus, v))
}

// RespStatusLTE applies the LTE predicate on the "resp_status" field.
func RespStatusLTE(v int) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldRespStatus, v))
}

// RespStatusIsNil applies the IsNil predicate on the "resp_status" field.
func RespStatusIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldRespStatus))
}

// RespStatusNotNil applies the NotNil predicate on the "resp_status" field.
func RespStatusNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldRespStatus))
}

// RespBodyIsNil applies the IsNil predicate on the "resp_body" field.
func RespBodyIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldRespBody))
}

// RespBodyNotNil applies the NotNil predicate on the "resp_body" field.
func RespBodyNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldRespBody))
}

// RespHeadersIsNil applies the IsNil predicate on the "resp_headers" field.
func RespHeadersIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldRespHeaders))
}

// RespHeadersNotNil applies the NotNil predicate on the "resp_headers" field.
func RespHeadersNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldRespHeaders))
}

// RespMetadataIsNil applies the IsNil predicate on the "resp_metadata" field.
func RespMetadataIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldRespMetadata))
}

// RespMetadataNotNil applies the NotNil predicate on the "resp_metadata" field.
func RespMetadataNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldRespMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Apireq {
	return predicate.Apireq(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Apireq {
	return predicate.Apireq(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Apireq) predicate.Apireq {
	return predicate.Apireq(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Apireq) predicate.Apireq {
	return predicate.Apireq(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Apireq) predicate.Apireq {
	return predicate.Apireq(sql.NotPredicates(p))
}
