// Code generated by ent, DO NOT EDIT.
package source

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the source type in the database.
	Label = "source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeSourceEarthquakes holds the string denoting the source_earthquakes edge name in mutations.
	EdgeSourceEarthquakes = "source_earthquakes"
	// Table holds the table name of the source in the database.
	Table = "source"
	// SourceEarthquakesTable is the table that holds the source_earthquakes relation/edge.
	SourceEarthquakesTable = "source_earthquake"
	// SourceEarthquakesInverseTable is the table name for the SourceEarthquake entity.
	// It exists in this package in order to avoid circular dependency with the "sourceearthquake" package.
	SourceEarthquakesInverseTable = "source_earthquake"
	// SourceEarthquakesColumn is the table column denoting the source_earthquakes relation/edge.
	SourceEarthquakesColumn = "s_id"
)

// Columns holds all SQL columns for source fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Source queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// BySourceEarthquakesCount orders the results by source_earthquakes count.
func BySourceEarthquakesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSourceEarthquakesStep(), opts...)
	}
}

// BySourceEarthquakes orders the results by source_earthquakes terms.
func BySourceEarthquakes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceEarthquakesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSourceEarthquakesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceEarthquakesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SourceEarthquakesTable, SourceEarthquakesColumn),
	)
}
