package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"gitlab.com/hedwig-phan/assignment-3/ent"
	"gitlab.com/hedwig-phan/assignment-3/graph"
)

// Earthquake is the resolver for the earthquake field.
func (r *ftypeEarthquakeResolver) Earthquake(ctx context.Context, obj *ent.FtypeEarthquake) (*ent.Earthquake, error) {
	panic(fmt.Errorf("not implemented: Earthquake - earthquake"))
}

// FeatureType is the resolver for the featureType field.
func (r *ftypeEarthquakeResolver) FeatureType(ctx context.Context, obj *ent.FtypeEarthquake) (*ent.FeatureType, error) {
	panic(fmt.Errorf("not implemented: FeatureType - featureType"))
}

// FtypeEarthquake returns graph.FtypeEarthquakeResolver implementation.
func (r *Resolver) FtypeEarthquake() graph.FtypeEarthquakeResolver {
	return &ftypeEarthquakeResolver{r}
}

type ftypeEarthquakeResolver struct{ *Resolver }
