// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.com/hedwig-phan/assignment-3/ent/earthquake"
	"gitlab.com/hedwig-phan/assignment-3/ent/predicate"
	"gitlab.com/hedwig-phan/assignment-3/ent/source"
	"gitlab.com/hedwig-phan/assignment-3/ent/sourceearthquake"
)

// SourceEarthquakeQuery is the builder for querying SourceEarthquake entities.
type SourceEarthquakeQuery struct {
	config
	ctx            *QueryContext
	order          []sourceearthquake.OrderOption
	inters         []Interceptor
	predicates     []predicate.SourceEarthquake
	withEarthquake *EarthquakeQuery
	withSource     *SourceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SourceEarthquakeQuery builder.
func (seq *SourceEarthquakeQuery) Where(ps ...predicate.SourceEarthquake) *SourceEarthquakeQuery {
	seq.predicates = append(seq.predicates, ps...)
	return seq
}

// Limit the number of records to be returned by this query.
func (seq *SourceEarthquakeQuery) Limit(limit int) *SourceEarthquakeQuery {
	seq.ctx.Limit = &limit
	return seq
}

// Offset to start from.
func (seq *SourceEarthquakeQuery) Offset(offset int) *SourceEarthquakeQuery {
	seq.ctx.Offset = &offset
	return seq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (seq *SourceEarthquakeQuery) Unique(unique bool) *SourceEarthquakeQuery {
	seq.ctx.Unique = &unique
	return seq
}

// Order specifies how the records should be ordered.
func (seq *SourceEarthquakeQuery) Order(o ...sourceearthquake.OrderOption) *SourceEarthquakeQuery {
	seq.order = append(seq.order, o...)
	return seq
}

// QueryEarthquake chains the current query on the "earthquake" edge.
func (seq *SourceEarthquakeQuery) QueryEarthquake() *EarthquakeQuery {
	query := (&EarthquakeClient{config: seq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := seq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := seq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sourceearthquake.Table, sourceearthquake.FieldID, selector),
			sqlgraph.To(earthquake.Table, earthquake.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sourceearthquake.EarthquakeTable, sourceearthquake.EarthquakeColumn),
		)
		fromU = sqlgraph.SetNeighbors(seq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySource chains the current query on the "source" edge.
func (seq *SourceEarthquakeQuery) QuerySource() *SourceQuery {
	query := (&SourceClient{config: seq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := seq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := seq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sourceearthquake.Table, sourceearthquake.FieldID, selector),
			sqlgraph.To(source.Table, source.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sourceearthquake.SourceTable, sourceearthquake.SourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(seq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SourceEarthquake entity from the query.
// Returns a *NotFoundError when no SourceEarthquake was found.
func (seq *SourceEarthquakeQuery) First(ctx context.Context) (*SourceEarthquake, error) {
	nodes, err := seq.Limit(1).All(setContextOp(ctx, seq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sourceearthquake.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) FirstX(ctx context.Context) *SourceEarthquake {
	node, err := seq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SourceEarthquake ID from the query.
// Returns a *NotFoundError when no SourceEarthquake ID was found.
func (seq *SourceEarthquakeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = seq.Limit(1).IDs(setContextOp(ctx, seq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sourceearthquake.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) FirstIDX(ctx context.Context) int {
	id, err := seq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SourceEarthquake entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SourceEarthquake entity is found.
// Returns a *NotFoundError when no SourceEarthquake entities are found.
func (seq *SourceEarthquakeQuery) Only(ctx context.Context) (*SourceEarthquake, error) {
	nodes, err := seq.Limit(2).All(setContextOp(ctx, seq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sourceearthquake.Label}
	default:
		return nil, &NotSingularError{sourceearthquake.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) OnlyX(ctx context.Context) *SourceEarthquake {
	node, err := seq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SourceEarthquake ID in the query.
// Returns a *NotSingularError when more than one SourceEarthquake ID is found.
// Returns a *NotFoundError when no entities are found.
func (seq *SourceEarthquakeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = seq.Limit(2).IDs(setContextOp(ctx, seq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sourceearthquake.Label}
	default:
		err = &NotSingularError{sourceearthquake.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) OnlyIDX(ctx context.Context) int {
	id, err := seq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SourceEarthquakes.
func (seq *SourceEarthquakeQuery) All(ctx context.Context) ([]*SourceEarthquake, error) {
	ctx = setContextOp(ctx, seq.ctx, "All")
	if err := seq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SourceEarthquake, *SourceEarthquakeQuery]()
	return withInterceptors[[]*SourceEarthquake](ctx, seq, qr, seq.inters)
}

// AllX is like All, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) AllX(ctx context.Context) []*SourceEarthquake {
	nodes, err := seq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SourceEarthquake IDs.
func (seq *SourceEarthquakeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if seq.ctx.Unique == nil && seq.path != nil {
		seq.Unique(true)
	}
	ctx = setContextOp(ctx, seq.ctx, "IDs")
	if err = seq.Select(sourceearthquake.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) IDsX(ctx context.Context) []int {
	ids, err := seq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (seq *SourceEarthquakeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, seq.ctx, "Count")
	if err := seq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, seq, querierCount[*SourceEarthquakeQuery](), seq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) CountX(ctx context.Context) int {
	count, err := seq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (seq *SourceEarthquakeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, seq.ctx, "Exist")
	switch _, err := seq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (seq *SourceEarthquakeQuery) ExistX(ctx context.Context) bool {
	exist, err := seq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SourceEarthquakeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (seq *SourceEarthquakeQuery) Clone() *SourceEarthquakeQuery {
	if seq == nil {
		return nil
	}
	return &SourceEarthquakeQuery{
		config:         seq.config,
		ctx:            seq.ctx.Clone(),
		order:          append([]sourceearthquake.OrderOption{}, seq.order...),
		inters:         append([]Interceptor{}, seq.inters...),
		predicates:     append([]predicate.SourceEarthquake{}, seq.predicates...),
		withEarthquake: seq.withEarthquake.Clone(),
		withSource:     seq.withSource.Clone(),
		// clone intermediate query.
		sql:  seq.sql.Clone(),
		path: seq.path,
	}
}

// WithEarthquake tells the query-builder to eager-load the nodes that are connected to
// the "earthquake" edge. The optional arguments are used to configure the query builder of the edge.
func (seq *SourceEarthquakeQuery) WithEarthquake(opts ...func(*EarthquakeQuery)) *SourceEarthquakeQuery {
	query := (&EarthquakeClient{config: seq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	seq.withEarthquake = query
	return seq
}

// WithSource tells the query-builder to eager-load the nodes that are connected to
// the "source" edge. The optional arguments are used to configure the query builder of the edge.
func (seq *SourceEarthquakeQuery) WithSource(opts ...func(*SourceQuery)) *SourceEarthquakeQuery {
	query := (&SourceClient{config: seq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	seq.withSource = query
	return seq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SID int `json:"s_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SourceEarthquake.Query().
//		GroupBy(sourceearthquake.FieldSID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (seq *SourceEarthquakeQuery) GroupBy(field string, fields ...string) *SourceEarthquakeGroupBy {
	seq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SourceEarthquakeGroupBy{build: seq}
	grbuild.flds = &seq.ctx.Fields
	grbuild.label = sourceearthquake.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SID int `json:"s_id,omitempty"`
//	}
//
//	client.SourceEarthquake.Query().
//		Select(sourceearthquake.FieldSID).
//		Scan(ctx, &v)
func (seq *SourceEarthquakeQuery) Select(fields ...string) *SourceEarthquakeSelect {
	seq.ctx.Fields = append(seq.ctx.Fields, fields...)
	sbuild := &SourceEarthquakeSelect{SourceEarthquakeQuery: seq}
	sbuild.label = sourceearthquake.Label
	sbuild.flds, sbuild.scan = &seq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SourceEarthquakeSelect configured with the given aggregations.
func (seq *SourceEarthquakeQuery) Aggregate(fns ...AggregateFunc) *SourceEarthquakeSelect {
	return seq.Select().Aggregate(fns...)
}

func (seq *SourceEarthquakeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range seq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, seq); err != nil {
				return err
			}
		}
	}
	for _, f := range seq.ctx.Fields {
		if !sourceearthquake.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if seq.path != nil {
		prev, err := seq.path(ctx)
		if err != nil {
			return err
		}
		seq.sql = prev
	}
	return nil
}

func (seq *SourceEarthquakeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SourceEarthquake, error) {
	var (
		nodes       = []*SourceEarthquake{}
		_spec       = seq.querySpec()
		loadedTypes = [2]bool{
			seq.withEarthquake != nil,
			seq.withSource != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SourceEarthquake).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SourceEarthquake{config: seq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, seq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := seq.withEarthquake; query != nil {
		if err := seq.loadEarthquake(ctx, query, nodes, nil,
			func(n *SourceEarthquake, e *Earthquake) { n.Edges.Earthquake = e }); err != nil {
			return nil, err
		}
	}
	if query := seq.withSource; query != nil {
		if err := seq.loadSource(ctx, query, nodes, nil,
			func(n *SourceEarthquake, e *Source) { n.Edges.Source = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (seq *SourceEarthquakeQuery) loadEarthquake(ctx context.Context, query *EarthquakeQuery, nodes []*SourceEarthquake, init func(*SourceEarthquake), assign func(*SourceEarthquake, *Earthquake)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SourceEarthquake)
	for i := range nodes {
		fk := nodes[i].EqID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(earthquake.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "eq_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (seq *SourceEarthquakeQuery) loadSource(ctx context.Context, query *SourceQuery, nodes []*SourceEarthquake, init func(*SourceEarthquake), assign func(*SourceEarthquake, *Source)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SourceEarthquake)
	for i := range nodes {
		fk := nodes[i].SID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(source.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "s_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (seq *SourceEarthquakeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := seq.querySpec()
	_spec.Node.Columns = seq.ctx.Fields
	if len(seq.ctx.Fields) > 0 {
		_spec.Unique = seq.ctx.Unique != nil && *seq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, seq.driver, _spec)
}

func (seq *SourceEarthquakeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sourceearthquake.Table, sourceearthquake.Columns, sqlgraph.NewFieldSpec(sourceearthquake.FieldID, field.TypeInt))
	_spec.From = seq.sql
	if unique := seq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if seq.path != nil {
		_spec.Unique = true
	}
	if fields := seq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourceearthquake.FieldID)
		for i := range fields {
			if fields[i] != sourceearthquake.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if seq.withEarthquake != nil {
			_spec.Node.AddColumnOnce(sourceearthquake.FieldEqID)
		}
		if seq.withSource != nil {
			_spec.Node.AddColumnOnce(sourceearthquake.FieldSID)
		}
	}
	if ps := seq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := seq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := seq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := seq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (seq *SourceEarthquakeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(seq.driver.Dialect())
	t1 := builder.Table(sourceearthquake.Table)
	columns := seq.ctx.Fields
	if len(columns) == 0 {
		columns = sourceearthquake.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if seq.sql != nil {
		selector = seq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if seq.ctx.Unique != nil && *seq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range seq.predicates {
		p(selector)
	}
	for _, p := range seq.order {
		p(selector)
	}
	if offset := seq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := seq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SourceEarthquakeGroupBy is the group-by builder for SourceEarthquake entities.
type SourceEarthquakeGroupBy struct {
	selector
	build *SourceEarthquakeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (segb *SourceEarthquakeGroupBy) Aggregate(fns ...AggregateFunc) *SourceEarthquakeGroupBy {
	segb.fns = append(segb.fns, fns...)
	return segb
}

// Scan applies the selector query and scans the result into the given value.
func (segb *SourceEarthquakeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, segb.build.ctx, "GroupBy")
	if err := segb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceEarthquakeQuery, *SourceEarthquakeGroupBy](ctx, segb.build, segb, segb.build.inters, v)
}

func (segb *SourceEarthquakeGroupBy) sqlScan(ctx context.Context, root *SourceEarthquakeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(segb.fns))
	for _, fn := range segb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*segb.flds)+len(segb.fns))
		for _, f := range *segb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*segb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := segb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SourceEarthquakeSelect is the builder for selecting fields of SourceEarthquake entities.
type SourceEarthquakeSelect struct {
	*SourceEarthquakeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ses *SourceEarthquakeSelect) Aggregate(fns ...AggregateFunc) *SourceEarthquakeSelect {
	ses.fns = append(ses.fns, fns...)
	return ses
}

// Scan applies the selector query and scans the result into the given value.
func (ses *SourceEarthquakeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ses.ctx, "Select")
	if err := ses.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SourceEarthquakeQuery, *SourceEarthquakeSelect](ctx, ses.SourceEarthquakeQuery, ses, ses.inters, v)
}

func (ses *SourceEarthquakeSelect) sqlScan(ctx context.Context, root *SourceEarthquakeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ses.fns))
	for _, fn := range ses.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ses.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ses.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
